### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by AranNomante** [AranNomante/Ch-to#4]
- [x] Private Messaging
    - [x] Message -> backend
    - [x] backend -> client
    - [x] client -> display
    - [x] chat switch
- [x] Room Messaging
    - [x] Room creation form
    - [x] Room creation
    - [x] Rooms & Subscription List & Ownership
    - [x] Join Room ( join socket to a room and add socket.id to sub list if not already in then don't join, capacity etc)
    - [x] If owner disconnects (no name tag) another person will be the owner 
    - [x] If there are no members in the room it will be deleted
    - [x] Room chat integration
- [x] Room actions such as disbanding the room
- [x] Room Video
- [x] Chat Emojis 

---------------Trivial
- [x] Chat panel fade out fade in on chat switch
- [x] Enter key submits message

These are all simplified version of many objectives to three objectives
